### ISSUE TITLE
"DateTime::__construct(): Failed to parse time string (06-23-2014) at position 0 (0): Unexpected character"

### ISSUE THREAD

**Issue by Lownin** [Sommerregen/grav-theme-machine#2]
Getting this error when attempting to use grav-theme-machine on fresh grav install.

`"DateTime::__construct(): Failed to parse time string (06-23-2014) at position 0 (0): Unexpected character"`

Highlights line 581 of system/src/Grav/Common/Utils.php

I'm running under MAMP on macOS.

![screen shot 2017-02-02 at 5 19 43 pm](https://cloud.githubusercontent.com/assets/8387063/22575648/cf4c8d1e-e96b-11e6-8fa7-3a59eb8f4068.png)

**Comment by Sommerregen** [comment]
Hi @Lownin,

I presume you are using the demo content right? As you can see the date error is coming from the file [blog_post.md file](https://github.com/Sommerregen/grav-theme-machine/blob/develop/_demo/pages/05.blog/06-23-2014-it-is-a-long-established-fact-that-a-reader-will-be-distracted/blog_post.md). I could recreate the error. At the time the demo content, Grav only supported a limited number of formats like `m-d-Y`. Now it can use any formats.

You have two possibilities now. Either you change the date in the above file to, e.g., `date: '2014-06-23'` or you can add the default format `pages.dateformat.default: 'm-d-Y'` into your `system.yaml`.

Sommerregen

---

For myself I add some code to recreate the problem in pure PHP.

```php
// The "right" way defining default datetimes
$datetime = new DateTime('2014-06-23');

// A Hack using pages.dateformat.default: 'm-d-Y'`
$datetime = DateTime::createFromFormat('m-d-Y', '06-23-2014');
```

**Comment by Lownin** [comment]
That worked.  Thank you.

**Comment by Sommerregen** [comment]
FYI: I just updated the theme and corrected the demo content. Thanks 👍

**Comment by webmastergta** [comment]
yetiforce 
Error!!!  DateTime::__construct(): Failed to parse time string (04-2018-10 08:00:00) at position 0 (0): Unexpected character
