### ISSUE TITLE
Hints for editing wanted

### ISSUE THREAD

**Issue by herrdeh** [Sommerregen/grav-theme-machine#3]
After some hours of struggle, I'm asking for help.
I choose grav, because it looks like a very easy way of creating a web page. Unluckily, it's not so easy to understand how to modify the theme to my needs.

So I think, quite some users would greatly appreciate some hints for basic editing the theme:

- how do I change the logo? (place yours into  /grav-admin/user/themes/machine/assets/images/logo.png)
- how do I change the colour of the headline ?
- how do I change the size of the used fonts?
- how do I change the contents of the top and the second headline (e.g. remove / replace the "phone" and "location" items - insert an image instead )? 

Some basic info would be very helpful!

Anyway - thanks for your work - greatly appreciated!
W

**Comment by Sommerregen** [comment]
Hi @herrdeh ,

almost all your questions can be tackled via CSS style changes. Currently, there is no way to do it in the admin or as a config parameter. Fist of all, I recommend using theme inheritance ( https://getgrav.org/blog/theme-development-with-inheritance ). Then, place your logo under `assets/images/logo.png`.

Styles for the headline can be found here [style.css#L340-L349](https://github.com/Sommerregen/grav-theme-machine/blob/develop/assets/css/style.css#L340-L349). You just have to modify it for your needs. The same goes for the `h2` headlines and so on. Fonts and font styles can also be changed there.

Generally, the contents can be changed by editing the page type twig templates, e.g., [default.html.twig](https://github.com/Sommerregen/grav-theme-machine/blob/develop/templates/default.html.twig). Adjusting [default.html.twig#L86-L104](https://github.com/Sommerregen/grav-theme-machine/blob/develop/templates/default.html.twig#L86-L104) to your needs is maybe all you want.

**Comment by herrdeh** [comment]
Hey, thank you very much for your reply - greatly appreciated. In the meanwhile, I figured out some of the items on my own - took me serveral hours, so my suggestion is to place the instructions you gave above into the readme.

Beste Grüße aus Berlin!

**Comment by Sommerregen** [comment]
@herrdeh Great! Can I close this issue in the meanwhile?

Viele Grüße zurück :-)

**Comment by herrdeh** [comment]
Yesss - fine with me!
